# Generated by Django 4.2.1 on 2023-05-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_cats_rename_user_name_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cats',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
