# Generated by Django 4.2.1 on 2023-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(null=True, upload_to='cats/info_cats'),
        ),
    ]
