# Generated by Django 4.2.1 on 2023-05-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_cats', '0002_alter_cat_description_alter_cat_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('publish_date', models.DateField(auto_now=True)),
                ('font', models.ImageField(upload_to='article_cat/font/%y/%m/%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_cats.cat')),
            ],
        ),
    ]
