# Generated by Django 4.2.1 on 2023-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_cats', '0003_articlecat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecat',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
