# Generated by Django 4.2.1 on 2023-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_cats', '0004_alter_articlecat_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecat',
            name='font',
            field=models.ImageField(blank=True, upload_to='article_cat/font/%y/%m/%d'),
        ),
    ]
