# Generated by Django 4.2.1 on 2023-06-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_cats', '0005_alter_articlecat_font'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecat',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterField(
            model_name='articlecat',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info_cats.cat'),
        ),
    ]
