# Generated by Django 4.2.1 on 2023-06-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info_cats', '0007_user_alter_articlecat_author_delete_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecat',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info_cats.user'),
        ),
    ]
