# Generated by Django 4.2.1 on 2023-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_cats', '0009_alter_user_options_user_password_user_password_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_2',
            field=models.CharField(max_length=16),
        ),
    ]
