# Generated by Django 4.2.1 on 2023-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_cats', '0010_alter_user_password_alter_user_password_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecat',
            name='font',
            field=models.ImageField(blank=True, default='default/user/404.jpeg', upload_to='article_cat/font/%y/%m/%d'),
        ),
    ]
