# Generated by Django 4.2.1 on 2023-06-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_initial'),
        ('info_cats', '0011_alter_articlecat_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecat',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
